"""empty message

Revision ID: 16cd7375be42
Revises: 260b6d36783c
Create Date: 2022-12-09 18:23:30.469507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cd7375be42'
down_revision = '260b6d36783c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geraete', sa.Column('info_geraet', sa.String(length=400), nullable=True))
    op.create_foreign_key(None, 'geraete', 'feuerwehren', ['id_feuerwehr'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'geraete', type_='foreignkey')
    op.drop_column('geraete', 'info_geraet')
    # ### end Alembic commands ###
