"""password_hash bei gerät eingefügt

Revision ID: 1b8b737faf87
Revises: 5641b5080795
Create Date: 2022-10-28 22:58:02.431768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8b737faf87'
down_revision = '5641b5080795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geraete', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geraete', 'password_hash')
    # ### end Alembic commands ###
