"""Feuerwehren und Benutzer anlegen

Revision ID: 7f6fc7696dc6
Revises: 1b8b737faf87
Create Date: 2022-10-29 11:30:20.714758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6fc7696dc6'
down_revision = '1b8b737faf87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feuerwehren',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('strasse', sa.String(length=30), nullable=False),
    sa.Column('plz', sa.Integer(), nullable=False),
    sa.Column('ort', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benutzer', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('id_feuerwehr', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_feuerwehr'], ['feuerwehren.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('benutzer')
    op.drop_table('feuerwehren')
    # ### end Alembic commands ###
