"""Geraete and Kurzpruefung table

Revision ID: f947b555a565
Revises: 
Create Date: 2022-06-22 20:30:41.998244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f947b555a565'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geraete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_geraet', sa.String(length=30), nullable=False),
    sa.Column('typ_geraet', sa.String(length=15), nullable=True),
    sa.Column('yyyy_geraet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_geraet')
    )
    op.create_table('kurzpruefung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zeit', sa.Date(), nullable=True),
    sa.Column('pruefer', sa.String(length=30), nullable=False),
    sa.Column('grund', sa.String(length=30), nullable=True),
    sa.Column('druck1', sa.Integer(), nullable=True),
    sa.Column('druck2', sa.Integer(), nullable=True),
    sa.Column('dichtheit', sa.Boolean(), nullable=True),
    sa.Column('warnsignal', sa.Boolean(), nullable=True),
    sa.Column('id_geraet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_geraet'], ['geraete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kurzpruefung_zeit'), 'kurzpruefung', ['zeit'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kurzpruefung_zeit'), table_name='kurzpruefung')
    op.drop_table('kurzpruefung')
    op.drop_table('geraete')
    # ### end Alembic commands ###
